### ISSUE TITLE
ReferenceError: robot is not defined

### ISSUE THREAD

**Issue by davesade** [catops/hubot-lgtm#6]
Hello.
I'm having this error:
```
ERROR ReferenceError: robot is not defined
  at notify (/hubot/node_modules/hubot-lgtm/src/lgtm.coffee:87:12, <js>:119:14)
  at /hubot/node_modules/hubot-lgtm/src/lgtm.coffee:48:12, <js>:52:16
  at /hubot/node_modules/github/lib/index.js:901:17
  at callCallback (/hubot/node_modules/github/lib/index.js:734:17)
  at IncomingMessage.<anonymous> (/hubot/node_modules/github/lib/index.js:799:25)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:905:12)
  at nextTickCallbackWith2Args (node.js:441:9)
  at process._tickCallback (node.js:355:17)
```

I use `export HUBOT_LGTM_NOTIFICATION_ROOM=some-room` as env var, so it seems to call `return robot.messageRoom room, msg`, but then `module.exports = (robot) ->` seems to be ignored - not sure why.

Am I missing something?

**Comment by davesade** [comment]
I don't have this issue anymore!
